/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as VisualShortIdRouteImport } from './routes/visual.$shortId'
import { Route as ThreadIdRouteImport } from './routes/thread.$id'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as DocShortIdRouteImport } from './routes/doc.$shortId'
import { Route as AboutPricingRouteImport } from './routes/about.pricing'
import { Route as AboutFeaturesRouteImport } from './routes/about.features'
import { Route as AboutDevelopersRouteImport } from './routes/about.developers'
import { Route as AboutAboutRouteImport } from './routes/about.about'
import { Route as ShareShareIdRawRouteImport } from './routes/share_.$shareId.raw'

const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const VisualShortIdRoute = VisualShortIdRouteImport.update({
  id: '/visual/$shortId',
  path: '/visual/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/thread/$id',
  path: '/thread/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocShortIdRoute = DocShortIdRouteImport.update({
  id: '/doc/$shortId',
  path: '/doc/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPricingRoute = AboutPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AboutRoute,
} as any)
const AboutFeaturesRoute = AboutFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AboutRoute,
} as any)
const AboutDevelopersRoute = AboutDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAboutRoute = AboutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AboutRoute,
} as any)
const ShareShareIdRawRoute = ShareShareIdRawRouteImport.update({
  id: '/share_/$shareId/raw',
  path: '/share/$shareId/raw',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRoute
  '/debug': typeof DebugRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/threads': typeof ThreadsRoute
  '/about/about': typeof AboutAboutRoute
  '/about/developers': typeof AboutDevelopersRoute
  '/about/features': typeof AboutFeaturesRoute
  '/about/pricing': typeof AboutPricingRoute
  '/doc/$shortId': typeof DocShortIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/thread/$id': typeof ThreadIdRoute
  '/visual/$shortId': typeof VisualShortIdRoute
  '/about/': typeof AboutIndexRoute
  '/share/$shareId/raw': typeof ShareShareIdRawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/debug': typeof DebugRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/threads': typeof ThreadsRoute
  '/about/about': typeof AboutAboutRoute
  '/about/developers': typeof AboutDevelopersRoute
  '/about/features': typeof AboutFeaturesRoute
  '/about/pricing': typeof AboutPricingRoute
  '/doc/$shortId': typeof DocShortIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/thread/$id': typeof ThreadIdRoute
  '/visual/$shortId': typeof VisualShortIdRoute
  '/about': typeof AboutIndexRoute
  '/share/$shareId/raw': typeof ShareShareIdRawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRoute
  '/debug': typeof DebugRoute
  '/integrations': typeof IntegrationsRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/threads': typeof ThreadsRoute
  '/about/about': typeof AboutAboutRoute
  '/about/developers': typeof AboutDevelopersRoute
  '/about/features': typeof AboutFeaturesRoute
  '/about/pricing': typeof AboutPricingRoute
  '/doc/$shortId': typeof DocShortIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/thread/$id': typeof ThreadIdRoute
  '/visual/$shortId': typeof VisualShortIdRoute
  '/about/': typeof AboutIndexRoute
  '/share_/$shareId/raw': typeof ShareShareIdRawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/debug'
    | '/integrations'
    | '/pricing'
    | '/settings'
    | '/sso-callback'
    | '/threads'
    | '/about/about'
    | '/about/developers'
    | '/about/features'
    | '/about/pricing'
    | '/doc/$shortId'
    | '/share/$shareId'
    | '/thread/$id'
    | '/visual/$shortId'
    | '/about/'
    | '/share/$shareId/raw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/debug'
    | '/integrations'
    | '/pricing'
    | '/settings'
    | '/sso-callback'
    | '/threads'
    | '/about/about'
    | '/about/developers'
    | '/about/features'
    | '/about/pricing'
    | '/doc/$shortId'
    | '/share/$shareId'
    | '/thread/$id'
    | '/visual/$shortId'
    | '/about'
    | '/share/$shareId/raw'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/debug'
    | '/integrations'
    | '/pricing'
    | '/settings'
    | '/sso-callback'
    | '/threads'
    | '/about/about'
    | '/about/developers'
    | '/about/features'
    | '/about/pricing'
    | '/doc/$shortId'
    | '/share/$shareId'
    | '/thread/$id'
    | '/visual/$shortId'
    | '/about/'
    | '/share_/$shareId/raw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AdminRoute: typeof AdminRoute
  DebugRoute: typeof DebugRoute
  IntegrationsRoute: typeof IntegrationsRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  ThreadsRoute: typeof ThreadsRoute
  DocShortIdRoute: typeof DocShortIdRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  ThreadIdRoute: typeof ThreadIdRoute
  VisualShortIdRoute: typeof VisualShortIdRoute
  ShareShareIdRawRoute: typeof ShareShareIdRawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/visual/$shortId': {
      id: '/visual/$shortId'
      path: '/visual/$shortId'
      fullPath: '/visual/$shortId'
      preLoaderRoute: typeof VisualShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$id': {
      id: '/thread/$id'
      path: '/thread/$id'
      fullPath: '/thread/$id'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$shortId': {
      id: '/doc/$shortId'
      path: '/doc/$shortId'
      fullPath: '/doc/$shortId'
      preLoaderRoute: typeof DocShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/pricing': {
      id: '/about/pricing'
      path: '/pricing'
      fullPath: '/about/pricing'
      preLoaderRoute: typeof AboutPricingRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/features': {
      id: '/about/features'
      path: '/features'
      fullPath: '/about/features'
      preLoaderRoute: typeof AboutFeaturesRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/developers': {
      id: '/about/developers'
      path: '/developers'
      fullPath: '/about/developers'
      preLoaderRoute: typeof AboutDevelopersRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/about': {
      id: '/about/about'
      path: '/about'
      fullPath: '/about/about'
      preLoaderRoute: typeof AboutAboutRouteImport
      parentRoute: typeof AboutRoute
    }
    '/share_/$shareId/raw': {
      id: '/share_/$shareId/raw'
      path: '/share/$shareId/raw'
      fullPath: '/share/$shareId/raw'
      preLoaderRoute: typeof ShareShareIdRawRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutAboutRoute: typeof AboutAboutRoute
  AboutDevelopersRoute: typeof AboutDevelopersRoute
  AboutFeaturesRoute: typeof AboutFeaturesRoute
  AboutPricingRoute: typeof AboutPricingRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAboutRoute: AboutAboutRoute,
  AboutDevelopersRoute: AboutDevelopersRoute,
  AboutFeaturesRoute: AboutFeaturesRoute,
  AboutPricingRoute: AboutPricingRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AdminRoute: AdminRoute,
  DebugRoute: DebugRoute,
  IntegrationsRoute: IntegrationsRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  ThreadsRoute: ThreadsRoute,
  DocShortIdRoute: DocShortIdRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  ThreadIdRoute: ThreadIdRoute,
  VisualShortIdRoute: VisualShortIdRoute,
  ShareShareIdRawRoute: ShareShareIdRawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
