import { mutationGeneric, queryGeneric } from "convex/server";
import { ConvexError, v } from "convex/values";

import { internalMutation, internalQuery } from "./_generated/server";
import { deleteDocumentBody, deleteHtmlBody } from "./artifactContent";
import { clearCompactionSummary } from "./threadCompaction";
import { threadLockValidator } from "./validators";

/* Locked threads: end-to-end encrypted chats.

   What this file can and cannot see is the entire design. The browser holds
   a content key derived from the user's password; every message body arrives
   here already sealed, and leaves the same way. Nothing on this side can
   read a locked conversation — not the title model, not memory, not search,
   not compaction, not us.

   The consequences are deliberate and enforced here rather than hoped for:

     - A locked thread runs plain chat only. Every tool we have writes its
       results into our tables in the clear — search sources, tool output,
       documents, generated images — so a locked thread gets none of them.
     - Its reply is generated by the tab that asked for it, over
       /locked-stream (convex/lockedInference.ts), because the plaintext
       transcript only exists in that tab. Nothing about the turn is
       scheduled, queued, or persisted mid-flight.
     - Only zero-retention models may serve it, so the plaintext we do hand
       a provider isn't kept there either.
     - The sidebar row is drawn from a neutral placeholder title; the real
       one is sealed alongside the messages.

   Locking an EXISTING thread is destructive on purpose: anything already
   written down that can't be sealed — attachments, artifacts, tool phases,
   the compaction summary, a live share link — is scrubbed rather than left
   sitting in the clear behind a lock icon. The setup modal says so plainly
   before the user commits. */

/** What the sidebar draws for a thread it has no key for. */
export const LOCKED_THREAD_TITLE = "Locked chat";

/** Statuses that mean a turn is still writing into the thread. */
const LIVE_STATUSES = new Set(["thinking", "searching", "streaming"]);

async function getCurrentUserId(ctx: any) {
  const identity = await ctx.auth.getUserIdentity();
  if (!identity) throw new ConvexError("Not authenticated");
  return identity.subject;
}

async function getOwnedThread(ctx: any, threadId: string) {
  const userId = await getCurrentUserId(ctx);
  const thread = await ctx.db.get(threadId);
  if (!thread || thread.userId !== userId) throw new Error("Thread not found");
  return { thread, userId };
}

/** Every message body the client re-sealed (or opened), by row. */
const bodiesValidator = v.array(
  v.object({ messageId: v.id("messages"), content: v.string() }),
);

/**
 * Strip everything in a thread that a lock can't cover. Attachments and
 * artifacts hold their contents in our storage in the clear; tool phases hold
 * search snippets, fetched pages and tool output as plain text. None of it can
 * be sealed after the fact and all of it would outlive the lock, so it goes.
 */
async function scrubUnsealable(ctx: any, threadId: string) {
  const [messages, docs, html] = await Promise.all([
    ctx.db
      .query("messages")
      .withIndex("by_thread_created_at", (q: any) => q.eq("threadId", threadId))
      .collect(),
    ctx.db
      .query("documents")
      .withIndex("by_thread", (q: any) => q.eq("threadId", threadId))
      .collect(),
    ctx.db
      .query("htmlArtifacts")
      .withIndex("by_thread", (q: any) => q.eq("threadId", threadId))
      .collect(),
  ]);

  for (const message of messages) {
    for (const attachment of message.attachments ?? []) {
      if (!attachment.storageId) continue;
      try {
        await ctx.storage.delete(attachment.storageId);
      } catch {
        // Already gone, or shared with a branched copy — never block the lock
        // on a stale blob id.
      }
    }
  }

  await Promise.all([
    ...docs.map(async (doc: any) => {
      await deleteDocumentBody(ctx, doc);
      await ctx.db.delete(doc._id);
    }),
    ...html.map(async (row: any) => {
      await deleteHtmlBody(ctx, row);
      await ctx.db.delete(row._id);
    }),
  ]);

  return messages;
}

/**
 * The key envelope for one thread, handed to the unlock dialog. Deliberately
 * its own query rather than a field on the sidebar listing: that listing reads
 * every thread a user owns and re-sends the lot on any write, and the envelope
 * is only ever wanted by the one dialog that's open.
 */
export const lockFor = queryGeneric({
  args: { threadId: v.id("threads") },
  handler: async (ctx, { threadId }) => {
    const { thread } = await getOwnedThread(ctx, threadId);
    if (!thread.lock) return null;
    return { lock: thread.lock, lockedTitle: thread.lockedTitle ?? null };
  },
});

/**
 * Turn a thread into a locked one. The client has already sealed every
 * message body and the title with a content key we never see; all that
 * arrives here is ciphertext plus the wrapped-key envelope.
 */
export const lockThread = mutationGeneric({
  args: {
    threadId: v.id("threads"),
    lock: threadLockValidator,
    /** The thread's current title, sealed. */
    lockedTitle: v.string(),
    /** Every existing message, re-sealed. All of them: a row missing from
     *  this list means the client read a different thread than the one
     *  being locked, and the lock is refused rather than guessed at. */
    bodies: bodiesValidator,
  },
  handler: async (ctx, { threadId, lock, lockedTitle, bodies }) => {
    const { thread } = await getOwnedThread(ctx, threadId);
    if (thread.lock) throw new ConvexError("This chat is already locked.");
    if (thread.incognito) {
      throw new ConvexError(
        "You cannot lock an incognito chat.",
      );
    }

    // A turn still writing would land plaintext on a row this mutation has
    // already sealed, straight past the lock. Checked before anything is
    // touched, so a refusal costs the thread nothing.
    const live = await ctx.db
      .query("messages")
      .withIndex("by_thread_role", (q: any) =>
        q.eq("threadId", threadId).eq("role", "assistant"),
      )
      .order("desc")
      .first();
    if (live && LIVE_STATUSES.has(live.status)) {
      throw new ConvexError(
        "Wait for the reply to complete. Then lock this chat.",
      );
    }

    const now = Date.now();
    const sealedBodies = new Map<string, string>(
      bodies.map((body) => [body.messageId, body.content]),
    );

    /* Every row has to have arrived sealed before anything is written. A
       gap means the client's read of the thread and this one disagree — a
       message landed in between, most likely — and the two ways to handle
       that are to delete what it couldn't seal or to stop. Deleting is
       silent data loss to save the user one retry, so: stop. Checked
       before the scrub, so a refusal leaves the thread untouched. */
    const preScrub = await ctx.db
      .query("messages")
      .withIndex("by_thread_created_at", (q: any) => q.eq("threadId", threadId))
      .collect();
    if (preScrub.some((message: any) => !sealedBodies.has(message._id))) {
      throw new ConvexError(
        "This chat changed during the lock operation. Try again.",
      );
    }

    const messages = await scrubUnsealable(ctx, threadId);

    for (const message of messages) {
      const sealed = sealedBodies.get(message._id);
      if (sealed === undefined) continue;
      await ctx.db.patch(message._id, {
        content: sealed,
        sealed: true,
        attachments: undefined,
        phases: message.role === "assistant" ? [] : undefined,
        updatedAt: now,
      });
    }

    await ctx.db.patch(threadId, {
      lock,
      lockedTitle,
      // The row still has to be drawable without the key.
      title: LOCKED_THREAD_TITLE,
      titleStatus: "ready",
      // A public link would outlive the lock entirely.
      shareId: undefined,
      // The summary is a plaintext retelling of the conversation.
      compactionBoundary: undefined,
      compactionMarkers: undefined,
      compactionStatus: undefined,
      compactionUpdatedAt: undefined,
      compactionSummary: undefined,
      updatedAt: now,
    });
    await clearCompactionSummary(ctx, threadId);

    return null;
  },
});

/**
 * Start a locked thread from nothing — the `/lock` path taken from home,
 * where there's no conversation to convert. Born locked, so no plaintext
 * ever passes through it.
 */
export const createLockedThread = mutationGeneric({
  args: { lock: threadLockValidator, lockedTitle: v.string() },
  handler: async (ctx, { lock, lockedTitle }) => {
    const userId = await getCurrentUserId(ctx);
    const now = Date.now();
    const threadId = await ctx.db.insert("threads", {
      userId,
      title: LOCKED_THREAD_TITLE,
      titleStatus: "ready",
      createdAt: now,
      updatedAt: now,
      lock,
      lockedTitle,
    });
    return { threadId };
  },
});

/**
 * Take the lock off. The client opened every body first and sends them back
 * as plain text — this is the one path that puts a locked conversation back
 * into readable storage, and it only runs on an explicit ask.
 */
export const removeLock = mutationGeneric({
  args: {
    threadId: v.id("threads"),
    /** The thread's real title, opened. */
    title: v.string(),
    bodies: bodiesValidator,
  },
  handler: async (ctx, { threadId, title, bodies }) => {
    const { thread } = await getOwnedThread(ctx, threadId);
    if (!thread.lock) return null;

    const now = Date.now();
    for (const body of bodies) {
      const message = await ctx.db.get(body.messageId);
      if (!message || message.threadId !== threadId) continue;
      await ctx.db.patch(body.messageId, {
        content: body.content,
        sealed: undefined,
        updatedAt: now,
      });
    }

    await ctx.db.patch(threadId, {
      lock: undefined,
      lockedTitle: undefined,
      title: title.trim() || LOCKED_THREAD_TITLE,
      updatedAt: now,
    });
    return null;
  },
});

/**
 * Swap in a re-wrapped envelope — a password change. The content key itself
 * doesn't move, so every sealed body stays valid and the printed recovery key
 * keeps working.
 */
export const setLockEnvelope = mutationGeneric({
  args: { threadId: v.id("threads"), lock: threadLockValidator },
  handler: async (ctx, { threadId, lock }) => {
    const { thread } = await getOwnedThread(ctx, threadId);
    if (!thread.lock) throw new ConvexError("This chat is not locked.");
    await ctx.db.patch(threadId, { lock });
    return null;
  },
});

/** Rename a locked thread. The name is sealed like everything else. */
export const setLockedTitle = mutationGeneric({
  args: { threadId: v.id("threads"), lockedTitle: v.string() },
  handler: async (ctx, { threadId, lockedTitle }) => {
    const { thread } = await getOwnedThread(ctx, threadId);
    if (!thread.lock) throw new ConvexError("This chat is not locked.");
    await ctx.db.patch(threadId, { lockedTitle });
    return null;
  },
});

/**
 * Open a locked turn: store the sealed prompt, mint the assistant row, and
 * stop there. No scheduled action, no stream row — the tab that sent this
 * holds the only copy of the plaintext, so the tab runs the turn
 * (convex/lockedInference.ts) and seals the reply on the way back.
 */
export const sendLockedMessage = mutationGeneric({
  args: {
    threadId: v.id("threads"),
    /** The user's message, sealed. */
    content: v.string(),
    model: v.string(),
    thinking: v.boolean(),
    /** First message only: the thread's name, sealed. */
    lockedTitle: v.optional(v.string()),
  },
  handler: async (ctx, { threadId, content, model, thinking, lockedTitle }) => {
    const { thread, userId } = await getOwnedThread(ctx, threadId);
    if (!thread.lock) throw new ConvexError("This chat is not locked.");

    const now = Date.now();
    const userMessageId = await ctx.db.insert("messages", {
      threadId,
      userId,
      role: "user",
      content,
      sealed: true,
      createdAt: now,
      updatedAt: now,
    });
    const assistantId = await ctx.db.insert("messages", {
      threadId,
      userId,
      role: "assistant",
      // Stays empty until the tab seals the finished reply onto it. A locked
      // reply is never written down mid-flight, in any form.
      content: "",
      createdAt: now + 1,
      updatedAt: now + 1,
      status: thinking ? "thinking" : "streaming",
      phases: [],
      model,
      thinking,
      search: false,
      // Liveness for the watchdog (convex/streamWatchdog.ts): the tab is the
      // handler here, and a closed tab has to be reaped like any other dead
      // turn rather than shimmering forever.
      heartbeatAt: now,
    });

    await ctx.db.patch(threadId, {
      updatedAt: now,
      model,
      ...(lockedTitle && !thread.lockedTitle ? { lockedTitle } : {}),
    });

    return { userMessageId, assistantId };
  },
});

/**
 * Land a finished locked reply: sealed text, terminal status, and the stats
 * the message footer shows. Called by the tab that ran the turn — including
 * when the user stops it early, so a half-written reply is still kept.
 */
export const finishLockedTurn = mutationGeneric({
  args: {
    threadId: v.id("threads"),
    assistantId: v.id("messages"),
    /** The reply, sealed. Empty means nothing was generated. */
    content: v.string(),
    status: v.union(
      v.literal("complete"),
      v.literal("stopped"),
      v.literal("error"),
    ),
    /** Plain text, ours not the model's — an error we wrote ourselves. */
    errorMessage: v.optional(v.string()),
    outputTokens: v.optional(v.number()),
    durationMs: v.optional(v.number()),
  },
  handler: async (
    ctx,
    { threadId, assistantId, content, status, errorMessage, outputTokens, durationMs },
  ) => {
    const { thread } = await getOwnedThread(ctx, threadId);
    if (!thread.lock) throw new ConvexError("This chat is not locked.");
    const message = await ctx.db.get(assistantId);
    if (!message || message.threadId !== threadId) {
      throw new Error("Message not found");
    }

    const now = Date.now();
    const failed = status === "error";
    await ctx.db.patch(assistantId, {
      // An error message is our own copy, so it rides in the clear and the
      // client renders it verbatim (nothing sealed to open).
      content: failed ? (errorMessage ?? "This reply did not complete.") : content,
      // Only a body that actually holds ciphertext is flagged sealed — a
      // stopped turn that produced nothing has an empty one, and claiming
      // otherwise would send the client looking for an envelope.
      sealed: !failed && content.length > 0 ? true : undefined,
      status,
      updatedAt: now,
      heartbeatAt: undefined,
      ...(outputTokens !== undefined ? { outputTokens } : {}),
      ...(durationMs !== undefined ? { durationMs } : {}),
    });
    await ctx.db.patch(threadId, { updatedAt: now });
    return null;
  },
});

/**
 * Rewrite a sent prompt in a locked thread. The replacement arrives sealed
 * like the original; regenerating the reply after it is `resetLockedTurn`.
 */
export const editLockedMessage = mutationGeneric({
  args: {
    threadId: v.id("threads"),
    messageId: v.id("messages"),
    /** The new text, sealed. */
    content: v.string(),
  },
  handler: async (ctx, { threadId, messageId, content }) => {
    const { thread } = await getOwnedThread(ctx, threadId);
    if (!thread.lock) throw new ConvexError("This chat is not locked.");
    const message = await ctx.db.get(messageId);
    if (!message || message.threadId !== threadId || message.role !== "user") {
      throw new Error("Message not found");
    }
    await ctx.db.patch(messageId, {
      content,
      sealed: true,
      updatedAt: Date.now(),
    });
    return null;
  },
});

/**
 * Wipe a locked reply back to pending so the tab can run it again. The
 * plaintext equivalent mints a stream and schedules a server turn; here
 * there's nothing to schedule — the tab takes it from the assistant row.
 */
export const resetLockedTurn = mutationGeneric({
  args: { threadId: v.id("threads"), assistantId: v.id("messages") },
  handler: async (ctx, { threadId, assistantId }) => {
    const { thread } = await getOwnedThread(ctx, threadId);
    if (!thread.lock) throw new ConvexError("This chat is not locked.");
    const message = await ctx.db.get(assistantId);
    if (
      !message ||
      message.threadId !== threadId ||
      message.role !== "assistant"
    ) {
      throw new Error("Message not found");
    }

    const now = Date.now();
    await ctx.db.patch(assistantId, {
      content: "",
      sealed: undefined,
      status: message.thinking ? "thinking" : "streaming",
      phases: [],
      usageCost: 0,
      heartbeatAt: now,
      updatedAt: now,
    });
    await ctx.db.patch(threadId, { updatedAt: now });
    return { assistantId };
  },
});

/** The tab saying it's still there, so the watchdog leaves the turn alone. */
export const beatLockedTurn = mutationGeneric({
  args: { threadId: v.id("threads"), assistantId: v.id("messages") },
  handler: async (ctx, { threadId, assistantId }) => {
    await getOwnedThread(ctx, threadId);
    const message = await ctx.db.get(assistantId);
    if (!message || message.threadId !== threadId) return null;
    await ctx.db.patch(assistantId, { heartbeatAt: Date.now() });
    return null;
  },
});

/* ---- what the turn handler reads ------------------------------------- */

/**
 * Everything /locked-stream needs to know before it spends anything: that the
 * caller owns a genuinely locked thread, and that the assistant row it was
 * handed is a real, still-pending turn in it.
 */
export const turnPreflight = internalQuery({
  args: {
    userId: v.string(),
    threadId: v.id("threads"),
    assistantId: v.id("messages"),
  },
  handler: async (ctx, { userId, threadId, assistantId }) => {
    const thread = await ctx.db.get(threadId);
    if (!thread || thread.userId !== userId) throw new Error("Thread not found");
    if (!thread.lock) throw new Error("This chat is not locked.");
    const message = await ctx.db.get(assistantId);
    if (!message || message.threadId !== threadId || message.role !== "assistant") {
      throw new Error("Message not found");
    }
    return {
      model: message.model ?? "Auto",
      thinking: message.thinking ?? false,
      status: message.status ?? "complete",
    };
  },
});

/** Heartbeat from the turn handler's side of the connection. */
export const beat = internalMutation({
  args: { assistantId: v.id("messages") },
  handler: async (ctx, { assistantId }) => {
    const message = await ctx.db.get(assistantId);
    if (!message) return null;
    await ctx.db.patch(assistantId, { heartbeatAt: Date.now() });
    return null;
  },
});

/**
 * Settle a locked turn that failed before the tab could seal anything —
 * a gate rejection, a provider error, a missing key. Written in the clear
 * because it's our copy, not the conversation.
 */
export const failTurn = internalMutation({
  args: { assistantId: v.id("messages"), message: v.string() },
  handler: async (ctx, { assistantId, message }) => {
    const row = await ctx.db.get(assistantId);
    if (!row) return null;
    await ctx.db.patch(assistantId, {
      status: "error",
      content: message,
      sealed: undefined,
      heartbeatAt: undefined,
      updatedAt: Date.now(),
    });
    return null;
  },
});

/** Stamp what a locked turn cost onto its message, for the usage tab. */
export const recordTurnCost = internalMutation({
  args: {
    assistantId: v.id("messages"),
    usageCost: v.number(),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    totalTokens: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const row = await ctx.db.get(args.assistantId);
    if (!row) return null;
    await ctx.db.patch(args.assistantId, {
      usageCost: args.usageCost,
      ...(args.inputTokens !== undefined ? { inputTokens: args.inputTokens } : {}),
      ...(args.outputTokens !== undefined
        ? { outputTokens: args.outputTokens }
        : {}),
      ...(args.totalTokens !== undefined ? { totalTokens: args.totalTokens } : {}),
    });
    return null;
  },
});
